spring.application.name: product
server:
  port: 7001
  error.include-message: always

spring.data:
  mongodb:
    host: localhost
    port: 27017
    database: product-db
#      uri: 'mongodb://root:example@localhost:27017/product-db?authSource=admin'

app.eureka-server: localhost
eureka:
  client:
    serviceUrl:
      defaultZone: http://${app.eureka-server}:8761/eureka/
    initialInstanceInfoReplicationIntervalSeconds: 5
    registryFetchIntervalSeconds: 5
  instance:
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 5

spring.cloud:
  config:
    enabled: false
  function.definition: messageProcessor
  stream:
    defaultBinder: kafka
    default.contentType: appdockelication/json
    bindings:
      messageProcessor-in-0:
        destination: products
        group: productsGroup
        consumer:
          maxAttempts: 3
          backOffInitialInterval: 500
          backOffMaxInterval: 1000
          backOffMultiplier: 2.0

spring.cloud.stream.kafka:
  bindings.messageProcessor-in-0.consumer:
    enableDlq: true
  binder:
    autoAddPartitions: true
    brokers: 127.0.0.1
    defaultBrokerPort: 9092

logging:
  level:
    root: INFO
    com.example: DEBUG
    org.springframework.data.mongodb.core.ReactiveMongoTemplate: DEBUG

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"